<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="JesnaHP" failures="1" tests="1" name="SeleniumProject" time="0.089" errors="0" timestamp="2024-11-02T00:58:01 IST">
  <testcase classname="com.automation.testng.LoginTest" name="verifyUserCannotLoginWithInvalidCred" time="0.02">
    <failure type="java.lang.AssertionError" message="expected [hg] but found [gh]">
      <![CDATA[java.lang.AssertionError: expected [hg] but found [gh]
at com.automation.testng.LoginTest.verifyUserCannotLoginWithInvalidCred(LoginTest.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCannotLoginWithInvalidCred -->
  <testcase classname="com.automation.testng.LoginTest" name="verifyUseCanLogout" time="0.0">
    <ignored/>
  </testcase> <!-- verifyUseCanLogout -->
  <testcase classname="com.automation.testng.LoginTest" name="verifyUserLogin" time="0.0">
    <ignored/>
  </testcase> <!-- verifyUserLogin -->
</testsuite> <!-- SeleniumProject -->
